CREATE TABLE webhooks (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 255 ),
    headers TEXT NOT NULL,
    body TEXT NOT NULL,
    upload_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
