language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test

before_install:
  - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -

matrix:
  include:
  - stage: Coverage
    script:
      - export CARGO_INCREMENTAL=0
      - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
      - cargo build $CARGO_OPTIONS
      - cargo test --verbose $CARGO_OPTIONS
      - |
        zip -0 ccov.zip `find . \( -name "hook-recorder*.gc*" \) -print`;
        ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
        bash <(curl -s https://codecov.io/bash) -f lcov.info;
    rust: nightly
